routes/web.php
<?php

use App\Http\Controllers\BlogsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;
use Whoops\Run;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/categories/{category}/blogs', [FrontendController::class, 'category'])
    ->name('frontend.category');
Route::get('/tags/{tag}/blogs', [FrontendController::class, 'tag'])
    ->name('frontend.tag');
Route::get('/blogs/{blog}', [FrontendController::class, 'show'])
    ->name('frontend.blogs.show');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::prefix('/admin')->name('admin.')->group(function() {
        Route::get('/dashboard', function() {
            return view('admin.dashboard');
        })->name('dashboard');

        Route::resource('categories', CategoriesController::class)->except(['show']);
        Route::resource('tags', TagsController::class)->except(['show']);

        Route::get('/blogs/trashed', [BlogsController::class, 'trashed'])->name('blogs.trashed');
        Route::resource('blogs', BlogsController::class);
        Route::delete('/blogs/{blog}/trash', [BlogsController::class, 'trash'])->name('blogs.trash');
        Route::put('/blogs/{blog}/restore', [BlogsController::class, 'restore'])->name('blogs.restore');
    });
});

require __DIR__.'/auth.php';

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Storage;

class Blog extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = []; //Isme jo bhi hum likhenge usko wo guard karega matlab fill nahi karne dega

    protected $casts = [
        'published_at' => 'datetime',
    ];

    // Relationship Methods
    public function author() {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function category() {
        return $this->belongsTo(Category::class);
    }

    public function tags() {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function getImagePathAttribute() {
        return '/storage/'.$this->attributes['image_path'];
    }

    public function deleteImage() {
        Storage::delete($this->attributes['image_path']);
    }

    public function scopePublished($query) {
        return $query->where('published_at', '<=', now());
    }

    public function scopeSearch($query) {
        $searchParam = request()->search;
        if($searchParam) {
            $query = $query->where('title', 'like', "%$searchParam%");
        }
        return $query;
    }
}

app/Http/Controllers/BlogsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Blog\CreateBlogRequest;
use App\Http\Requests\Blog\UpdateBlogRequest;
use App\Http\Requests\UpdateTagRequest;
use App\Models\Blog;
use App\Models\Category;
use App\Models\Tag;
use Illuminate\Http\Request;

class BlogsController extends Controller
{

    public function __construct()
    {
        $this->middleware(['validateAuthor'])->only(['edit', 'update', 'destroy', 'trash']);
    }
    public function index() {
        $authUser = auth()->user();
        if($authUser->isAdmin()) {
            $blogs = Blog::with('category')->latest()->paginate(10);
        } else {
            $blogs = Blog::with('category')
                        ->where('user_id', $authUser->id)
                        ->latest()
                        ->paginate(10);
        }

        return view('admin.blogs.index', compact('blogs'));
    }

    public function create() {
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.blogs.create', compact([
            'categories',
            'tags'
        ]));
    }

    public function store(CreateBlogRequest $request) {
        // Image Upload and return the name of the file which will be created
        $image_path = $request->file('image')->store('blogs');
        $data = $request->only(['title', 'excerpt', 'body', 'category_id', 'published_at']);

        $data = array_merge($data, [
            'image_path'=>$image_path,
            'user_id'=>auth()->user()->id
        ]);

        $blog = Blog::create($data);
        $blog->tags()->attach($request->tags);

        session()->flash('success', 'Blog created successfully...');
        return redirect(route('admin.blogs.index'));
    }

    public function edit(Blog $blog) {
        $categories = Category::all();
        $tags = Tag::all();

        return view('admin.blogs.edit', compact([
            'categories',
            'tags',
            'blog'
        ]));
    }

    public function update(UpdateBlogRequest $request, Blog $blog) {
        $data = $request->only(['title', 'excerpt', 'body', 'category_id', 'published_at']);

        if($request->hasFile('image')) {
            $image_path = $request->file('image')->store('blogs');
            $blog->deleteImage();
            $data = array_merge($data, ['image_path'=>$image_path]);
        }

        $blog->update($data);
        $blog->tags()->sync($request->tags);

        session()->flash('success', 'Blog updated successfully...');
        return redirect(route('admin.blogs.index'));

    }

    public function trash(Blog $blog) {
        $blog->delete();

        session()->flash('success', 'Blog deleted successfully...');
        return redirect(route('admin.blogs.index'));
    }

    public function destroy(int $blogId) {
        $blog = Blog::onlyTrashed()->find($blogId);
        $blog->deleteImage();
        $blog->forceDelete();

        session()->flash('success', 'Blog destroyed successfully...');
        return redirect(route('admin.blogs.trashed'));
    }

    public function trashed() {
        $blogs = Blog::with('category')
            ->where('user_id', auth()->id())
            ->onlyTrashed()
            ->latest()
            ->paginate(10);

        return view('admin.blogs.trashed', compact('blogs'));
    }

    public function restore(int $blogId) {
        $blog = Blog::withTrashed()->find($blogId);
        $blog->restore();

        session()->flash('success', 'Blog Restored successfully...');
        return redirect(route('admin.blogs.index'));
    }
}

resources/views/admin/blogs/create.blade.php
@extends('admin.layout.app')

@section('styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
@endsection

@section('scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>

    <script>
        $('.select2').select2({
            placeholder: "Select a value",
            allowClear: true
        });
        flatpickr("#published_at",{
            enableTime: true,
            altInput: true,
            altFormat: 'F j, Y H:i',
            dateFormat: 'Y-m-d H:i',
        });
    </script>
@endsection

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-item-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Add New Blog</h1>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.blogs.store') }}"  method="POST" enctype="multipart/form-data">
                    @csrf
                    {{-- title --}}
                    <div class="form-group">
                        <label for="title" class="form-label">Title</label>
                        <input
                        type="text"
                        value="{{ old('title') }}"
                        class="form-control @error('title') border-danger text-danger @enderror"
                        placeholder="Enter title"
                        name="title"
                        id="title">
                        @error('title')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of title --}}

                    {{-- excerpt --}}
                    <div class="form-group">
                        <label for="excerpt" class="form-label">Excerpt</label>
                        <input
                        type="text"
                        value="{{ old('excerpt') }}"
                        class="form-control @error('excerpt') border-danger text-danger @enderror"
                        placeholder="Enter Excerpt"
                        name="excerpt"
                        id="excerpt">
                        @error('excerpt')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of excerpt --}}

                    {{-- body --}}
                    <div class="form-group">
                        <label for="body" class="form-label">Body</label>
                        <input
                        type="hidden"
                        value="{{ old('body') }}"
                        class="form-control @error('body') border-danger text-danger @enderror"
                        placeholder="Enter body"
                        name="body"
                        id="body">
                        <trix-editor input="body"></trix-editor>

                        @error('body')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of body --}}

                    {{-- category id --}}
                    <div class="form-group">
                        <label for="category_id" class="form-label">Category</label>
                        <select name="category_id" id="category_id" class="form-control select2">
                            <option></option>
                            @foreach ($categories as $category)
                                @if ($category->id == old('category_id'))
                                    <option value="{{ $category->id }}" selected>{{ $category->name }}
                                    </option>
                                @else
                                    <option value="{{ $category->id }}">{{ $category->name }}
                                    </option>
                                @endif
                            @endforeach
                        </select>
                        @error('category_id')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of category id --}}

                    {{-- tags --}}
                    <div class="form-group">
                        <label for="tags" class="form-label">Tags</label>
                        <select name="tags[]" id="tags" class="form-control select2" multiple>
                            <option></option>
                            @foreach ($tags as $tag)
                                <option value="{{ $tag->id }}"
                                {{ old('tags') && in_array($tag->id, old('tags')) ? 'selected' : '' }}>
                                {{ $tag->name }}
                            </option>
                            @endforeach
                        </select>
                        @error('tags')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of tags --}}

                    {{-- published at --}}
                    <div class="form-group">
                        <label for="published_at" class="form-label">Published At</label>
                        <input
                        type="date"
                        value="{{ old('published_at') }}"
                        class="form-control @error('published_at') border-danger text-danger @enderror"
                        placeholder="Enter Published Date"
                        name="published_at"
                        id="published_at">

                        @error('published_at')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of published at --}}

                    {{-- image file --}}
                    <div class="form-group">
                        <label for="image_path" class="form-label">Image</label>
                        <input
                        type="file"
                        class="form-control @error('image_path') border-danger text-danger @enderror"
                        placeholder="Select Image File"
                        name="image"
                        id="image_path">
                        @error('image')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of image file --}}

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" name="addBlog">Submit</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/blogs/edit.blade.php
@extends('admin.layout.app')

@section('styles')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
@endsection

@section('scripts')
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>

    <script>
        $('.select2').select2({
            placeholder: "Select a value",
            allowClear: true
        });
        flatpickr("#published_at",{
            enableTime: true,
            altInput: true,
            altFormat: 'F j, Y H:i',
            dateFormat: 'Y-m-d H:i',
        });
    </script>
@endsection

@section('main-content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="d-sm-flex align-item-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Edit Blog</h1>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('admin.blogs.update', $blog->id) }}"  method="POST" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    {{-- title --}}
                    <div class="form-group">
                        <label for="title" class="form-label">Title</label>
                        <input
                        type="text"
                        value="{{ old('title', $blog->title) }}"
                        class="form-control @error('title') border-danger text-danger @enderror"
                        placeholder="Enter title"
                        name="title"
                        id="title">
                        @error('title')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of title --}}

                    {{-- excerpt --}}
                    <div class="form-group">
                        <label for="excerpt" class="form-label">Excerpt</label>
                        <input
                        type="text"
                        value="{{ old('excerpt', $blog->excerpt) }}"
                        class="form-control @error('excerpt') border-danger text-danger @enderror"
                        placeholder="Enter Excerpt"
                        name="excerpt"
                        id="excerpt">
                        @error('excerpt')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of excerpt --}}

                    {{-- body --}}
                    <div class="form-group">
                        <label for="body" class="form-label">Body</label>
                        <input
                        type="hidden"
                        value="{{ old('body', $blog->body) }}"
                        class="form-control @error('body') border-danger text-danger @enderror"
                        placeholder="Enter body"
                        name="body"
                        id="body">
                        <trix-editor input="body"></trix-editor>

                        @error('body')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of body --}}

                    {{-- category id --}}
                    <div class="form-group">
                        <label for="category_id" class="form-label">Category</label>
                        <select name="category_id" id="category_id" class="form-control select2">
                            <option></option>
                            @foreach ($categories as $category)
                                @if ($category->id == old('category_id', $blog->category_id))
                                    <option value="{{ $category->id }}" selected>{{ $category->name }}
                                    </option>
                                @else
                                    <option value="{{ $category->id }}">{{ $category->name }}
                                    </option>
                                @endif
                            @endforeach
                        </select>
                        @error('category_id')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of category id --}}

                    {{-- tags --}}
                    <div class="form-group">
                        <label for="tags" class="form-label">Tags</label>
                        <select name="tags[]" id="tags" class="form-control select2" multiple>
                            <option></option>
                            @foreach ($tags as $tag)
                                <option value="{{ $tag->id }}"
                                {{ in_array($tag->id, old('tags', $blog->tags()->pluck('tags.id')->toArray())) ? 'selected' : '' }}>
                                {{ $tag->name }}
                            </option>
                            @endforeach
                        </select>
                        @error('tags')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of tags --}}

                    {{-- published at --}}
                    <div class="form-group">
                        <label for="published_at" class="form-label">Published At</label>
                        <input
                        type="date"
                        value="{{ old('published_at', $blog->published_at) }}"
                        class="form-control @error('published_at') border-danger text-danger @enderror"
                        placeholder="Enter Published Date"
                        name="published_at"
                        id="published_at">

                        @error('published_at')
                            <span class="text-danger">
                                {{ $message }}
                            </span>
                        @enderror
                    </div>
                    {{-- end of published at --}}

                    {{-- image file --}}
                    <div class="row">
                        <div class="col-md-4">
                            <img src="{{ asset($blog->image_path)}}" alt="" width="100%">
                        </div>
                        <div class="col-md-8">
                            <div class="form-group">
                                <label for="image_path" class="form-label">Image</label>
                                <input
                                type="file"
                                class="form-control @error('image_path') border-danger text-danger @enderror"
                                placeholder="Select Image File"
                                name="image"
                                id="image_path">
                                @error('image')
                                    <span class="text-danger">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    {{-- end of image file --}}

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" name="addBlog">Submit</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/blogs/trashed.blade.php
@extends('admin.layout.app')
@section('main-content')
<div class="container-fluid">
    <!--  Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Blogs</h1>
        <a href="{{ route('admin.blogs.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
            class="fas fa-plus fa-sm text-white-50"></i>Create Blog</a>
    </div>
    <!-- END OF PAGE HEADING -->

    <div class="row">
        <div class="col-md-12">
            @include('admin.layout._alert-messages')
            <table class="table table-bordered table-responsive">
                <thead>
                    <th>ID</th>
                    <th>Image</th>
                    <th>Title</th>
                    <th>Excerpt</th>
                    <th>Category</th>
                    <th>Actions</th>
                </thead>
                <tbody>
                    @foreach ($blogs as $blog)
                        <tr>
                            <td>{{ $blog->id }}</td>
                            <td>
                                <img src="{{ asset($blog->image_path) }}" alt="{{ $blog->title }}" width="80px">
                            </td>
                            <td> {{ $blog->title }} </td>
                            <td> {{ $blog->excerpt }} </td>
                            <td> {{ $blog->category->name }} </td>
                            <td>
                                <button class="btn btn-warning" data-toggle="modal" data-target="#restoreModal" onClick="restoreModalHelper('{{route('admin.blogs.restore', $blog->id) }}' )">
                                    <i class="fa fa-recycle"></i>
                                </button>

                                <button class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" onClick="deleteModalHelper('{{route('admin.blogs.destroy', $blog->id) }}' )">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            @if($blogs->count() == 0)
                <p>No Blogs Found</p>
            @endif
            {{ $blogs->links('vendor.pagination.bootstrap-5')}}
        </div>
    </div>
</div>

{{-- DELETE Modal --}}
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form method="POST" action="" id="deleteForm">
                @csrf
                @method('DELETE')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Blog?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to delete Blog?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-danger" type="submit">Delete</button>
                    </div>
                </div>
            </form>
        </div>
</div>

{{-- RESTORE Modal --}}
<div class="modal fade" id="restoreModal" tabindex="-1" role="dialog" aria-labelledby="restoreModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form method="POST" action="" id="restoreForm">
                @csrf
                @method('PUT')
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="restoreModalLabel">Restore Blog?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Are you sure you want to restore Blog?</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <button class="btn btn-warning" type="submit">Restore</button>
                    </div>
                </div>
            </form>
        </div>
</div>

@endsection

@section('scripts')
<script>
    function deleteModalHelper(url) {
        document.getElementById("deleteForm").setAttribute('action', url);
    }

    function restoreModalHelper(url) {
        document.getElementById("restoreForm").setAttribute('action', url);
    }
</script>

@endsection