routes/web.php
<?php

use App\Http\Controllers\BlogsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\TagsController;
use Illuminate\Support\Facades\Route;
use Whoops\Run;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [FrontendController::class, 'index'])->name('home');
Route::get('/categories/{category}/blogs', [FrontendController::class, 'category'])
    ->name('frontend.category');
Route::get('/tags/{tag}/blogs', [FrontendController::class, 'tag'])
    ->name('frontend.tag');
Route::get('/blogs/{blog}', [FrontendController::class, 'show'])
    ->name('frontend.blogs.show');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::prefix('/admin')->name('admin.')->group(function() {
        Route::get('/dashboard', function() {
            return view('admin.dashboard');
        })->name('dashboard');

        Route::resource('categories', CategoriesController::class)->except(['show']);
        Route::resource('tags', TagsController::class)->except(['show']);

        Route::get('/blogs/trashed', [BlogsController::class, 'trashed'])->name('blogs.trashed');
        Route::resource('blogs', BlogsController::class);
        Route::delete('/blogs/{blog}/trash', [BlogsController::class, 'trash'])->name('blogs.trash');
        Route::put('/blogs/{blog}/restore', [BlogsController::class, 'restore'])->name('blogs.restore');
    });
});

require __DIR__.'/auth.php';

app/Http/Controllers/FrontendController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\Category;
use App\Models\Tag;
use Illuminate\Http\Request;

class FrontendController extends Controller
{
    public function index() {
        $blogs = Blog::with('author')->search()->published()
                    ->orderBy('published_at','desc')->simplePaginate(3);
        $categories = Category::withCount('blogs')->get();
        $tags = Tag::limit(10)->get();
        return view('frontend.index',compact([ 'categories', 'tags', 'blogs' ]));
    }

    public function category(Category $category) {
        $blogs = $category->blogs()->search()->published()->simplePaginate(3);
        $categories = Category::withCount('blogs')->get();
        $tags = Tag::limit(10)->get();
        return view('frontend.index', compact(['categories', 'tags', 'blogs']));
    }

    public function tag(Tag $tag) {
        $blogs = $tag->blogs()->search()->published()->simplePaginate(3);
        $categories = Category::withCount('blogs')->get();
        $tags = Tag::limit(10)->get();
        return view('frontend.index', compact(['categories', 'tags', 'blogs']));
    }

    public function show(Blog $blog) {
        $blogTags = $blog->tags;

        $categories = Category::withCount('blogs')->get(); # for sidebar
        $tags = Tag::limit(10)->get(); # for sidebar
        return view('frontend.blog', compact(['categories', 'tags', 'blog', 'blogTags']));
    }

}

resources/views/frontend/layout/_footer.blade.php
<!-- Footer Area
=====================================-->
<footer id="footer" class="footer-one center-block bg-light pt50 pb30 ">
    <div class="container">
        <div class="row">

            <div class="col-md-2 col-xs-12 mb25">
                <div class="navbar-brand-footer center-block">Pen-It</div>
                <div class="copyright center-block">&copy; 2020. All rights reserved.</div>
            </div>

            <div class="col-md-8 col-xs-12 text-center">
                <div class="row">
                    <div class="col-sm-12">
                        <ul class=" bb-solid-1">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Post</a></li>
                        </ul>
                    </div>

                    <div class="col-sm-12 mt25">
                        <ul>
                            <li><a href="#">Help Center</a></li>
                            <li><a href="#">Knowledgebase</a></li>
                            <li><a href="#">Term of Service</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">FAQs</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-md-2 col-xs-12">
                <div class="social-container">
                    <ul class="footer-social text-center">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-github"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>

        </div>

    </div>
</footer>

resources/views/frontend/layout/_nav.blade.php
<!-- Navigation Area
===================================== -->
<nav class="navbar navbar-pasific navbar-mp megamenu navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">
                <img src="{{ asset('frontend/assets/img/logo/logo-default.png')}}" alt="logo">
                Pen-It
            </a>
        </div>

        <div class="navbar-collapse collapse navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="index.html" data-toggle="dropdown" class="dropdown-toggle color-light">Home </a>
                </li>
                <li>
                    <a href="{{ route('login') }}" class="dropdown-toggle color-light">Login</a>
                </li>
            </ul>

        </div>
    </div>
</nav>

resources/views/frontend/layout/_sidebar.blade.php
<!-- Blog Sidebar
            ===================================== -->
            <div id="sidebar" class="col-md-3 mt50 animated" data-animation="fadeInRight" data-animation-delay="250">


                <!-- Search
                ===================================== -->
                <div class="pr25 pl25 clearfix">
                    <form action="{{ Route::currentRouteName() == 'frontend.blogs.show' ? route('home') : '#'}}">
                        <div class="blog-sidebar-form-search">
                            <input type="text" name="search" value="{{ request()->search }}" class="" placeholder="e.g. Javascript">
                            <button type="submit" class="pull-right"><i class="fa fa-search"></i></button>
                        </div>
                    </form>

                </div>


                <!-- Categories
                ===================================== -->
                <div class="mt25 pr25 pl25 clearfix">
                    <h5 class="mt25">
                        Categories
                        <span class="heading-divider mt10"></span>
                    </h5>
                    <ul class="blog-sidebar pl25">
                        @foreach ($categories as $category)
                            <li>
                                <a href="{{ route('frontend.category', $category->id )}}">{{$category->name}}<span class="badge badge-pasific pull-right">{{$category->blogs_count}}</span></a>
                            </li>
                        @endforeach
                    </ul>

                </div>


                <!-- Tags
                ===================================== -->
                <div class="pr25 pl25 clearfix">
                    <h5 class="mt25">
                        Popular Tags
                        <span class="heading-divider mt10"></span>
                    </h5>
                    <ul class="tag">
                        @foreach ($tags as $tag)
                        <li><a href="{{ route('frontend.tag', $tag->id)}}">{{ $tag->name }}</a></li>
                        @endforeach
                    </ul>

                </div>
            </div>

resources/views/frontend/layout/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Pen-It | Bloggers Heaven</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="utf-8">
    <meta name="author" content="John Doe">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

    <!-- Favicons -->
    <link rel="shortcut icon" href="{{ asset('frontend/assets/img/favicon.png')}}">
    <link rel="apple-touch-icon" href="{{ asset('frontend/assets/img/apple-touch-icon.png')}}">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ asset('frontend/assets/img/apple-touch-icon-72x72.png')}}">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ asset('frontend/assets/img/apple-touch-icon-114x114.png')}}">

    <!-- Load Core CSS
    =====================================-->
    <link rel="stylesheet" href="{{ asset('frontend/assets/css/core/bootstrap-3.3.7.min.css')}}">
    <link rel="stylesheet" href="{{ asset('frontend/assets/css/core/animate.min.css')}}">

    <!-- Load Main CSS
    =====================================-->
    <link rel="stylesheet" href="{{ asset('frontend/assets/css/main/main.css')}}">
    <link rel="stylesheet" href="{{ asset('frontend/assets/css/main/setting.css')}}">
    <link rel="stylesheet" href="{{ asset('frontend/assets/css/main/hover.css')}}">


    <link rel="stylesheet" href="{{ asset('frontend/assets/css/color/pasific.css')}}">
    <link rel="stylesheet" href="{{ asset('frontend/assets/css/icon/font-awesome.css')}}">
    <link rel="stylesheet" href="{{ asset('frontend/assets/css/icon/et-line-font.css')}}">

    @yield('styles')

    <!-- Load JS
    HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries
    WARNING: Respond.js doesn't work if you view the page via file://
    =====================================-->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body id="topPage" data-spy="scroll" data-target=".navbar" data-offset="100">



<!-- Page Loader
===================================== -->
<div id="pageloader" class="bg-grad-animation-1">
    <div class="loader-item">
        <img src="{{ asset('frontend/assets/img/other/oval.svg')}}" alt="page loader">
    </div>
</div>

<a href="#page-top" class="go-to-top">
    <i class="fa fa-long-arrow-up"></i>
</a>


@include('frontend.layout._nav')


@yield('content')

@include('frontend.layout._footer')


<!-- JQuery Core
=====================================-->
<script src="{{ asset('frontend/assets/js/core/jquery.min.js')}}"></script>
<script src="{{ asset('frontend/assets/js/core/bootstrap-3.3.7.min.js')}}"></script>

<!-- Magnific Popup
=====================================-->
<script src="{{ asset('frontend/assets/js/magnific-popup/jquery.magnific-popup.min.js')}}"></script>
<script src="{{ asset('frontend/assets/js/magnific-popup/magnific-popup-zoom-gallery.js')}}"></script>

<!-- JQuery Main
=====================================-->
<script src="{{ asset('frontend/assets/js/main/jquery.appear.js')}}"></script>
<script src="{{ asset('frontend/assets/js/main/isotope.pkgd.min.js')}}"></script>
<script src="{{ asset('frontend/assets/js/main/parallax.min.js')}}"></script>
<script src="{{ asset('frontend/assets/js/main/jquery.sticky.js')}}"></script>
<script src="{{ asset('frontend/assets/js/main/imagesloaded.pkgd.min.js')}}"></script>
<script src="{{ asset('frontend/assets/js/main/main.js')}}"></script>

@yield('scripts')
</body>
</html>